use_frameworks!
platform :ios, '10.0'

target 'BryceNetworking_Example' do
  pod 'BryceNetworking', :path => '../'
  pod 'BryceNetworking/Promises', :path => '../'
  
  pod 'PromiseKit'
  pod 'PromiseKit/Alamofire'
  pod 'CodableAlamofire'

  target 'BryceNetworking_Tests' do
    inherit! :search_paths

    
  end
end
